version: '3.6'

services:

  konstellation-node:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: konstellation-node
    container_name: konstellation-node
    restart: always
    ports:
      - 1317:1317
      - 9090:9090
      - 9091:9091
      - 26656:26656
      - 26657:26657
    volumes:
      - ./config:/workspace/.knstld/config
      - /mnt/${VOLUME_NAME}/knstl-sentry/.knstld/data:/workspace/.knstld/data
      - /mnt/${VOLUME_NAME}/knstl-sentry/.knstld/wasm:/workspace/.knstld/wasm
    command: >
      bash -c "
      [ ! -f "/workspace/.knstld/config/genesis.json" ] && cp /default_config/config/* /workspace/.knstld/config/ || :
      && sed -i -e '/moniker =/ s/= .*/= \"${NODE_MONIKER}\"/' /workspace/.knstld/config/config.toml
      && cd /workspace/.knstld
      && /bin/knstld start --home ./
      "