version: '3.6'

services:

  konstellation-node:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: konstellation-node
    container_name: konstellation-node
    restart: always
    ports:
      - 1317:1317
      - 9090:9090
      - 9091:9091
      - 26656:26656
      - 26657:26657
    volumes:
      - ./config:/workspace/.knstld/config
      - /mnt/${VOLUME_NAME}/knstl-sentry/.knstld/data:/workspace/.knstld/data
      - /mnt/${VOLUME_NAME}/knstl-sentry/.knstld/wasm:/workspace/.knstld/wasm
    command: >
      bash -c "
      cd /workspace/.knstld 
      && /bin/knstld version
      && /bin/knstld init '${NODE_MONIKER}' --home ./ --chain-id=darchub -o 
      && cp /config/genesis.json /workspace/.knstld/config/genesis.json
      && cp /config/config.toml /workspace/.knstld/config/config.toml
      && sed -i -e '/moniker =/ s/= .*/= \"${NODE_MONIKER}\"/' /workspace/.knstld/config/config.toml
      && sed -i '/\[instrumentation\]/{:a;n;/prometheus/s/false/true/;Ta}' /workspace/.knstld/config/config.toml
      && sed -i 's/pruning = \x22default\x22/pruning = \x22nothing\x22/' /workspace/.knstld/config/app.toml
      && sed -i '/\[grpc\]/,+3 s/enable = false/enable = true/;/\[api\]/,+3 s/enable = false/enable = true/;/\[rosetta\]/,+3 s/enable = true/enable = true/' /workspace/.knstld/config/app.toml
      && /bin/knstld start --home ./
      "